---
spring:
  application:
    name: cook
  cloud:
    config:
        enabled: false 

encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme

management:
  endpoints:
    web:
      exposure:
        include: '*'

# management:
#   server:
#     port: 8080
#     ssl:
#       enabled: false
#   endpoint:
#     health:
#       probes:
#         enabled: true
#   health:
#     livenessState:
#       enabled: true
#     readinessState:
#       enabled: true
